swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  '/user/transaction/:id':
    get:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Fetch specific transactions
      description: API for fetch specific transaction by id
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: query
          name: Transaction ID
          description: Specify transaction id
          type: integer
          required: true
      responses:
        "200":
          description: Transaction fetched successully
          schema:
            $ref: "#/definitions/FetchTransactionResponse"
        "400":
          description: Invalid Fields
        "404":
          description: Transaction not found
        "401":
          description: Unauthorized access
        "500":
          description: Internal Server Error
  /user/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Fetch monthly transactions
      description: API for fetch transactions during current month
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: parameter
          required: true
          schema:
            properties:
              month:
                type: integer
                default: 6
      responses:
        "200":
          description: Transactions fetched successully
          schema:
            $ref: "#/definitions/FetchTransactionResponse"
        "401":
          description: Unauthorized access
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Add transaction informations
      description: API for add informations to specific transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Specify transaction id
          required: true
          schema:
            $ref: "#/definitions/TransactionAllSelectionHandle"
      produces:
        - application/json
      responses:
        "200":
          description: Transaction informations added successully
          schema:
            $ref: "#/definitions/HandledTransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized access
        "500":
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Update transaction informations
      description: API for update informations to specific transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/TransactionSelectionHandle"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/HandledTransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized access
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User transaction Module
      summary: Delete transaction
      description: API for update informations to specific transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: query
          name: Transaction ID
          description: Specify transaction id
          type: integer
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile deleted successully
          schema:
            $ref: "#/definitions/HandledTransactionResponse"
        "400":
          description: Invalid Fields
        "401":
          description: Unauthorized access
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  TransactionSelectionHandle:
    properties:
      transactionId:
        type: integer
        default: 123
        description: transaction id
      informations:
        type: object
        properties:
          '':
            type: object
            properties:
              type:
                type: string
              content:
                type: string
  TransactionAllSelectionHandle:
    properties:
      informations:
        type: object
        properties:
          '':
            type: object
            properties:
              type:
                type: string
              content:
                type: string
  HandledTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
  FetchTransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: object
            properties:
              id:
                type: string
              receiver:
                type: string
              amount:
                type: integer
              comment:
                type: string
              createdAt:
                type: string
              updatedAt:
                type: string
